import typography from '@tailwindcss/typography';

const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/mdx-components.tsx",
  ],
  plugins: [
    typography({
      className: 'prose',
    }),
  ],
  future: {
    hoverOnlyWhenSupported: true,
    respectDefaultRingColorOpacity: true,
    disableColorOpacityUtilitiesByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  safelist: [
    'grid-cols-1',
    'sm:grid-cols-2',
    'md:grid-cols-2',
    'lg:grid-cols-1',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'xl:grid-cols-2',
    'xl:grid-cols-3',
    'xl:grid-cols-5',
    '2xl:grid-cols-3',
    'mobile:grid-cols-1',
    'mobile:grid-cols-2',
    'tablet:grid-cols-2',
    'tablet:grid-cols-3',
    'desktop:grid-cols-3',
    'desktop:grid-cols-4',
    'large:grid-cols-4',
    'large:grid-cols-5',
    'large:grid-cols-6',
    'gap-3',
    'gap-4',
    'sm:gap-4',
    'sm:gap-6',
    'mobile:gap-mobile-sm',
    'mobile:gap-mobile-md',
    'tablet:gap-tablet-md',
    'tablet:gap-tablet-lg',
    'desktop:gap-desktop-md',
    'desktop:gap-desktop-lg',
    'large:gap-large-md',
    'large:gap-large-lg',
    'touch-manipulation',
    'min-h-touch-small',
    'min-h-touch-medium',
    'min-h-touch-large',
    'min-w-touch-small',
    'min-w-touch-medium',
    'min-w-touch-large',
    'min-h-[44px]',
    'min-h-[32px]',
    'min-h-[36px]',
    'min-h-[24px]',
    'min-h-[28px]',
    'min-h-[20px]',
    'min-h-[280px]',
    'sm:min-h-[320px]',
    'md:min-h-[360px]',
    'mobile:min-h-[240px]',
    'tablet:min-h-[320px]',
    'desktop:min-h-[400px]',
    'large:min-h-[480px]',
    'text-mobile-base',
    'text-mobile-lg',
    'text-tablet-base',
    'text-tablet-lg',
    'text-desktop-base',
    'text-desktop-lg',
    'text-large-base',
    'text-large-lg',
    'p-mobile-md',
    'p-tablet-md',
    'p-desktop-md',
    'p-large-md',
    'px-mobile-md',
    'px-tablet-md',
    'px-desktop-md',
    'px-large-md',
    'py-mobile-md',
    'py-tablet-md',
    'py-desktop-md',
    'py-large-md',
    'm-mobile-md',
    'm-tablet-md',
    'm-desktop-md',
    'm-large-md',
    'mx-mobile-md',
    'mx-tablet-md',
    'mx-desktop-md',
    'mx-large-md',
    'my-mobile-md',
    'my-tablet-md',
    'my-desktop-md',
    'my-large-md',
    'touch:opacity-75',
    'mouse:hover:opacity-80',
    'mobile-touch:text-lg',
    'desktop-mouse:hover:scale-105',
    'reduced-motion:transition-none',
    'high-contrast:border-2',
  ],
  theme: {
    screens: {
      'mobile': { 'max': '768px' },
      'tablet': { 'min': '769px', 'max': '1024px' },
      'desktop': { 'min': '1025px', 'max': '1440px' },
      'large': { 'min': '1441px' },
      'touch': { 'raw': '(hover: none) and (pointer: coarse)' },
      'mouse': { 'raw': '(hover: hover) and (pointer: fine)' },
      'mobile-touch': { 'raw': '(max-width: 768px) and (hover: none)' },
      'desktop-mouse': { 'raw': '(min-width: 1025px) and (hover: hover)' },
      'portrait': { 'raw': '(orientation: portrait)' },
      'landscape': { 'raw': '(orientation: landscape)' },
      'reduced-motion': { 'raw': '(prefers-reduced-motion: reduce)' },
      'high-contrast': { 'raw': '(prefers-contrast: high)' },
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      spacing: {
        'mobile-xs': '0.5rem',
        'mobile-sm': '0.75rem',
        'mobile-md': '1rem',
        'mobile-lg': '1.5rem',
        'mobile-xl': '2rem',
        'tablet-xs': '0.75rem',
        'tablet-sm': '1rem',
        'tablet-md': '1.5rem',
        'tablet-lg': '2rem',
        'tablet-xl': '3rem',
        'desktop-xs': '1rem',
        'desktop-sm': '1.5rem',
        'desktop-md': '2rem',
        'desktop-lg': '3rem',
        'desktop-xl': '4rem',
        'large-xs': '1.5rem',
        'large-sm': '2rem',
        'large-md': '3rem',
        'large-lg': '4rem',
        'large-xl': '6rem',
      },
      minHeight: {
        'touch-small': '44px',
        'touch-medium': '48px',
        'touch-large': '56px',
      },
      minWidth: {
        'touch-small': '44px',
        'touch-medium': '48px',
        'touch-large': '56px',
      },
      fontSize: {
        'mobile-xs': ['0.75rem', { lineHeight: '1rem' }],
      },
      maxWidth: {},
      gridTemplateColumns: {},
      typography: {},
    },
  },
};

export default config;
