# Cloudflare Pages 配置文件
name = "iflux-art"
compatibility_date = "2025-05-24"
main = "index.js"  # 替换 site.entry-point

# 构建配置
[build]
command = "pnpm build"

# 环境变量
[vars]
NODE_VERSION = "20.11.1"

# 路由配置 - 修复为正确的格式
[[routes]]
pattern = "/*"
zone_name = "web.zx-14f.workers.dev"  # 替换为您的实际域名

# 自定义域名配置
[site]
bucket = ".next"
# entry-point 字段已移除，改用顶级 main 字段

# 缓存配置 - 移至 [site.cache]
[site.cache]
caching = true
preview_cache_revalidate = "manual"
production_cache_revalidate = "manual"
