# Cloudflare Pages 配置文件
name = "web"  # 修改为与 CI 系统期望的名称一致
compatibility_date = "2025-05-24"
main = "index.js"  # 入口点文件

# 构建配置
[build]
command = "pnpm build"

# 环境变量
[vars]
NODE_VERSION = "20.11.1"

# 自定义域名配置
[site]
bucket = ".next"

# 排除大文件，解决文件大小限制问题
[site.include]
"*" = true

[site.exclude]
"cache/**" = true  # 排除所有缓存文件
"server/**/*.pack" = true
"webpack/**/*.pack" = true
