/**
 * 配置文件统一导出
 */

// 元数据配置
export {
  SITE_METADATA,
  SITE_AUTHOR,
  SITE_URL,
  SITE_TWITTER,
  SITE_GITHUB,
  SITE_EMAIL,
  SITE_COPYRIGHT,
  VIEWPORT_CONFIG,
  IOS_CONFIG,
  WINDOWS_CONFIG,
} from "./metadata";

// 页面元数据配置
export {
  HOME_PAGE_METADATA,
  LINKS_PAGE_METADATA,
  ABOUT_PAGE_METADATA,
  FRIENDS_PAGE_METADATA,
  DOCS_PAGE_METADATA,
  BLOG_PAGE_METADATA,
  PROFILE_PAGE_METADATA,
  PAGE_METADATA_MAP,
} from "./page-metadata";
